server:
  port: 9002

spring:
  application:
    name: demo-api-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/demo}
    username: us_root
    password: YLweX9QoDWHVRkzpMGndGBqm
  liquibase:
    enabled: true
    change-log: classpath:data/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://${eureka.hostname:localhost}:8761/eureka

demo:
  oauth:
    jwt:
      public-key: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQAB-----END PUBLIC KEY-----
  user:
    oauth:
      clientId: client id
      clientSecret: secret